### ISSUE TITLE
About the files you modified

### ISSUE THREAD

**Issue by YUECHE77** [Shwai-He/RESSA#1]
Hello,

Thanks for your amazing work! Could you tell me which files you modified please? For example, which files did you do the pruning for the models, and which files you did SparseLoRA finetuning.

Thank you so much!!!!!

**Comment by Shwai-He** [comment]
Hello,

Thank you for your encouraging words! The pruning code can be found in lavis/compression/pruners, and the SparseLoRA code is located at lavis/peft/src/peft/tuners/lora.py.

**Comment by YUECHE77** [comment]
Got it! Thank you!
